language: python

python: 
  - "3.6"

matrix:
  fast_finish: true

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# command to run tests using coverage
script: pytest --cov=beauty_ocean

after_success:
  - pytest --cov=beauty_ocean
